module mod_tutorial_smoothbump
#include <messenger.h>
    use mod_kinds,              only: ik, rk
    use mod_string,             only: string_t
    use type_bc_state_group,    only: bc_state_group_t
    use mod_test_utilities,     only: create_mesh_file
    use type_bc_state,          only: bc_state_t
    use mod_bc,                 only: create_bc
    use mod_io
    implicit none



    character(:),   allocatable :: step1
    character(:),   allocatable :: step2
    character(:),   allocatable :: step2_note
    character(:),   allocatable :: step3
    character(:),   allocatable :: step3_1
    character(:),   allocatable :: step3_2
    character(:),   allocatable :: step3_3
    character(:),   allocatable :: step4
    character(:),   allocatable :: step4_1
    character(:),   allocatable :: step4_2
    character(:),   allocatable :: step5
    character(:),   allocatable :: step5_1
    character(:),   allocatable :: step5_2
    character(:),   allocatable :: step6

    character(:),   allocatable :: command_string





contains


    !>  A ChiDG tutorial on the problem: Inviscid flow over a smooth bump.
    !!
    !!  @author Nathan A. Wukie
    !!  @date   4/28/2017
    !!
    !!
    !!
    !!
    !----------------------------------------------------------------------------
    subroutine tutorial_driver_smoothbump()

        integer(ik)     :: step
        logical         :: done, read_input
        character(1024) :: user_input


        step1 = "This tutorial investigates the problem of inviscid flow over a smooth &
                 bump in a channel. Since the flow is inviscid and subsonic, there should &
                 be no entropy generated in the problem. However, the solution of the &
                 discretized problem will have some entropy generated. We can use the &
                 ammount of entropy generated in the numerical solution as an error metric &
                 for determining the order of accuracy for the numerical scheme."

        step2 = "A multi-block, double-precision, unformatted Plot3D grid for this problem &
                 has been created and is stored in the file, 'smooth_bump.x'. The Plot3D &
                 grid was generated with extra resolution so that the points can be agglomerated &
                 by ChiDG to create quartic, curved elements. The Plot3D grid generally needs &
                 to be generated by the user. The Plot3D grid must be converted to a ChiDG format &
                 using the 'convert' utility as 'chidg convert smooth_bump.x' and then the boundary &
                 conditions can be added and set in the 'edit' utility as 'chidg edit smooth_bump.h5'. & 
                 This has been done for you here and the ChiDG grid is stored in 'smooth_bump_setup.h5' &
                 with the boundary condition functions and patch groups already set up. You may get a &
                 feel for the conversion and edit process by running the 'convert' action on the Plot3D &
                 grid(chidg convert smooth_bump.x) and then 'edit' the generated file to set &
                 boundary conditions(chidg edit smooth_bump.h5). For now we will use the file &
                 'smooth_bump_setup.h5' that has already been converted and set up. You can use this &
                 file as a reference and view the setup by running 'chidg edit smooth_bump_setup.h5'."
        step2_note = "You may investigate the contents of the generated HDF5 file by running the &
                      action 'chidg edit smooth_bump_setup.h5' in another terminal. Just make sure to &
                      exit the edit session before proceeding with this tutorial, since only one process &
                      may access the file at any given time."


        step3 = "Run the ChiDG calculation. In a separate terminal, navigate to the directory that the &
                 tutorial is running in. Run the ChiDG executable. If the executable is in your path: &
                 ( user@:~$ chidg )."
        step3_1 = "1) ChiDG searches for 'chidg.nml' and obtains the name of the grid files. Also initializes solver settings."
        step3_2 = "2) From the file specified in 'chidg.nml', ChiDG reads the grid and initializes data."
        step3_3 = "3) ChiDG runs the calculation."

        step4 = "Once the calculation is finished, in the same terminal and in the same tutorial directory, &
                 we want to post-process the solution for visualization. Run the ChiDG post-processing action &
                 ( user@:~$ chidg post smooth_bump_setup.h5 smooth_bump_setup.h5)"
        step4_1 = "The ChiDG post-processing action(chidg post) expects a grid file and a solution file. In this &
                   case, they are the same."
        step4_2 = "The post-processing step generates data in Tecplot and VTK format. The VTK files can be viewed &
                   using the open-source visulization tool Paraview."

        step5 = "Other resources."
        step5_1 = "International Workshop on High-Order CFD Methods: https://how4.cenaero.be/content/bi2-inviscid-flow-over-bump"
        step6 = "The End."

        !command_string = "Commands:  Forward(f-Enter), Backward(b-Enter), Quit(q-Enter)"
        command_string = "Enter command: "


        step = 1
        done = .false.
        do

            ! Execute step
            call smoothbump_stepper(step,done)

            ! Detect last step and exit
            if (done) exit



        
            ! Wait for user to indicate next step
            read_input = .true.
            do while (read_input)

                read(*,'(A1024)') user_input

                ! Go forward/backward
                if (trim(user_input) == 'f') then
                    step = step + 1
                    read_input = .false.
                else if (trim(user_input) == 'b') then
                    step = step - 1
                    read_input = .false.
                else if (trim(user_input) == 'q') then
                    step = 0
                    read_input = .false.
                end if

            end do




            !! Set step bounds
            !if (step < 1) step = 1

        end do

    end subroutine tutorial_driver_smoothbump
    !****************************************************************************






    !>
    !!
    !!
    !!
    !!
    !!
    !----------------------------------------------------------------------------
    subroutine smoothbump_stepper(step,done)
        integer(ik),    intent(in)      :: step
        logical,        intent(inout)   :: done

        type(string_t)                  :: group_names(1,6)
        type(bc_state_group_t)          :: bc_state_groups(3)
        class(bc_state_t),  allocatable :: bc_state

        ! Header
        call execute_command_line('clear')
        call write_smoothbump_header()
        call write_line('Step ', step, color='blue', bold=.true.)
        !call write_line(' ', ltrim=.false.)

        ! Step
        select case(step)

            case(1)
                call write_line(step1, width=100, color='blue')




            case(2)


                call write_line(step2, width=100, color='blue')
                call write_line(' ', ltrim=.false.)


                !
                ! Setup boundary conditions
                !
                bc_state_groups(1)%name = 'Inlet'
                bc_state_groups(2)%name = 'Outlet'
                bc_state_groups(3)%name = 'Walls'


                call create_bc('Inlet - Total', bc_state)
                call bc_state%set_fcn_option('Total Pressure',   'val', 110000._rk)
                call bc_state%set_fcn_option('Total Temperature','val', 300._rk   )
                call bc_state_groups(1)%add_bc_state(bc_state)

                call create_bc('Outlet - Constant Pressure', bc_state)
                call bc_state%set_fcn_option('Static Pressure', 'val', 93000._rk )
                call bc_state_groups(2)%add_bc_state(bc_state)

                call create_bc('Wall', bc_state)
                call bc_state_groups(3)%add_bc_state(bc_state)


                ! Define patch group names
                group_names(1,:) = [string_t('Inlet') , &
                                    string_t('Outlet'), &
                                    string_t('Walls') , &
                                    string_t('Walls') , &
                                    string_t('Walls') , &
                                    string_t('Walls') ]

                !
                ! Create grid file
                !
                call write_line("Creating grid file:", width=90, color='blue', bold=.true.)
                call create_mesh_file(selector        = "Smooth Bump",          &
                                      filename        = 'smooth_bump_setup.h5', &
                                      equation_sets   = [string_t("Euler")],    &
                                      group_names     = group_names,            &
                                      bc_state_groups = bc_state_groups,        &
                                      nelem_xi        = 15,                     &
                                      nelem_eta       = 8,                      &
                                      nelem_zeta      = 1,                      &
                                      save_intermediate_files = .true.)
                call write_line(" ", width=90, color='blue', ltrim=.false.)



                !
                ! Set namelist values and write to chidg.nml                
                !
                gridfile         = 'smooth_bump_setup.h5'
                solutionfile_out = 'smooth_bump_setup.h5'
                solution_order   = 3
                gq_rule          = 2
                time_integrator  = 'steady'
                nonlinear_solver = 'quasi-newton'
                cfl0             = 1.0
                ntol             = 1.e-5
                linear_solver    = 'fgmres'
                ltol             = 1.e-9
                preconditioner   = 'ILU0'


                call write_line("Creating namelist input file: 'chidg.nml'", width=90, color='blue', bold=.true.)
                call write_line(" ", width=90, color='blue', bold=.true., ltrim=.false.)
                call write_namelist()


                call write_line("Equivalent steps:", color='blue', bold=.true.)
                call write_line("   - Create Plot3D grid, smooth_bump.x.",                  color='blue', ltrim=.false.)
                call write_line("   - Convert Plot3D grid to HDF5. 'chidg convert grid.x'", color='blue', ltrim=.false.)
                call write_line("   - Edit boundary conditions. 'chidg edit grid.h5'",      color='blue', ltrim=.false.)
                call write_line(" ", width=90, color='blue', ltrim=.false.)

                call write_line("Note:", color='blue', bold=.true.)
                call write_line(step2_note, width=100, color='blue')









            case(3)
                call write_line(step3, width=90, color='blue')
                call write_line(' ', ltrim=.false.)
                call write_line('During execution:', width=90, color='blue', bold=.true.)
                call write_line(step3_1, width=90, color='blue')
                call write_line(step3_2, width=90, color='blue')
                call write_line(step3_3, width=90, color='blue')



            case(4)
                call write_line(step4, width=90, color='blue')
                call write_line(' ', ltrim=.false.)
                call write_line(step4_1, width=90, color='blue')
                call write_line(' ', ltrim=.false.)
                call write_line(step4_2, width=90, color='blue')



            case(5)
                call write_line(step5, width=90, color='blue')
                call write_line(' ', ltrim=.false.)
                call write_line(step5_1, width=150, color='blue')



            case(6)
                call write_line(step6, width=90, color='blue')



            case default
                done = .true.
                call execute_command_line('clear')



        end select

        !! Footer
        call write_line(' ', ltrim=.false.)
        call write_line(command_string, color='blue', bold=.true.)


        ! Done 
        if (done) call execute_command_line('clear')

    end subroutine smoothbump_stepper
    !****************************************************************************








    !>
    !!
    !!  @author Nathan A. Wukie
    !!  @date   4/28/2017
    !!
    !!
    !----------------------------------------------------------------------------
    subroutine write_smoothbump_header()

        call write_line('---------------------------------------------------------------------------',ltrim=.false.)
        call write_line('                                                                           ',ltrim=.false.)
        call write_line('   Title:        Smooth bump                                               ',ltrim=.false., bold=.true.)
        call write_line('   Equation set: Euler                                                     ',ltrim=.false., bold=.true.)
        call write_line('   Files:        smooth_bump.x, smooth_bump_setup.h5, chidg.nml            ',ltrim=.false., bold=.true.)
        call write_line('                                                                           ',ltrim=.false.)
        call write_line('   Configuration:                                                          ',ltrim=.false., bold=.true.)
        call write_line('                                   Wall                                    ',ltrim=.false.)
        call write_line('                       ___________________________                         ',ltrim=.false.)
        call write_line('                      |                           |                        ',ltrim=.false.)
        call write_line('   Total Pressure     |         Flow --->         |  Constant Pressure     ',ltrim=.false.)
        call write_line('   Total Temperature  |           _____           |                        ',ltrim=.false.)
        call write_line('                      |__________/     \__________|                        ',ltrim=.false.)
        call write_line('                                   Wall                                    ',ltrim=.false.)
        call write_line('                                                                           ',ltrim=.false.)
        call write_line('   Character commands to control the tutorial:                             ',ltrim=.false., bold=.true.)
        call write_line('       f (Forward)                                                         ',ltrim=.false.)
        call write_line('       b (Backward)                                                        ',ltrim=.false.)
        call write_line('       q (Quit)                                                            ',ltrim=.false.)
        call write_line('                                                                           ',ltrim=.false.)
        call write_line('---------------------------------------------------------------------------',ltrim=.false.)

    end subroutine write_smoothbump_header
    !****************************************************************************


end module mod_tutorial_smoothbump
